[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scrapy_cffi"
version = "0.3.3"
description = "An asyncio-style web scraping framework inspired by Scrapy, powered by curl_cffi."
authors = [{name = "aFunnyStrange"}]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "curl_cffi>=0.7.4,<=0.13.0",
    "PyExecjs",
    "orjson",
    "json5",
    "toml",
    "pydantic>=2.0.0",
    "jinja2",
    "tenacity",
    "redis>=5.0.0",
    "parsel",
    "regex",
    "python-dotenv"
]
[project.optional-dependencies]
media = ["filetype", "Pillow", "hachoir"]
kafka = ["aiokafka>=0.8.1"]
rabbitmq = ["aio-pika>=9.0"]
mysql = ["sqlalchemy[asyncio]>=2.0", "asyncmy>=0.2"]
postgres = ["sqlalchemy[asyncio]>=2.0", "asyncpg>=0.29"]
mongodb = ["motor>=3.7.1"]

[project.urls]
Homepage = "https://github.com/aFunnyStrange/scrapy_cffi"

[tool.setuptools.packages.find]
include = ["scrapy_cffi", "scrapy_cffi.*"]
exclude = ["docs*", "tests*", "examples*"]

[project.scripts]
scrapy-cffi = "scrapy_cffi.commands.main:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"scrapy_cffi" = ["templates/*", "templates/**/*", "templates/**/.*"]
"scrapy_cffi.cpy" = ["cpy_resources/**/*"]

[tool.setuptools.exclude-package-data]
"*" = ["__pycache__/*", "*.py[cod]"]
[tool.pytest.ini_options]
testpaths = ["tests"]
