"""Project-local Docker manager generated by ``scrapy-cffi demo``."""

import argparse
import os
from pathlib import Path
import re
import signal
import socket
import subprocess
import sys
import time
from typing import Dict, List, NamedTuple, Optional

import toml

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from demo_support.topology import DEMO_MODE


INFRA = ROOT / "infra"
TOPOLOGIES = ("single", "sentinel", "cluster")


class Stack(NamedTuple):
    name: str
    compose_file: Path
    services: List[str]


def project_prefix() -> str:
    config_path = ROOT / "scrapy_cffi.toml"
    prefix = "scrapy_cffi"
    if config_path.is_file():
        configured = toml.load(config_path).get("default", {}).get(
            "infra_project_name"
        )
        if isinstance(configured, str) and configured.strip():
            prefix = configured
    slug = re.sub(r"[^a-z0-9_-]+", "_", prefix.lower()).strip("_")
    return slug or "scrapy_cffi"


def stacks(topology: str) -> List[Stack]:
    prefix = project_prefix()
    if DEMO_MODE == "memory":
        return []

    result = []
    if topology == "single":
        services = ["redis"]
        if DEMO_MODE == "rabbitmq":
            services.append("rabbitmq")
        elif DEMO_MODE == "kafka":
            services.append("kafka")
        result.append(
            Stack(
                "%s_single" % prefix,
                INFRA / "docker-compose.yml",
                services,
            )
        )
        return result

    redis_name = "redis-sentinel" if topology == "sentinel" else "redis-cluster"
    result.append(
        Stack(
            "%s_%s" % (prefix, redis_name.replace("-", "_")),
            INFRA / redis_name / "docker-compose.yml",
            [],
        )
    )
    if DEMO_MODE == "rabbitmq":
        if topology == "cluster":
            result.append(
                Stack(
                    "%s_rabbitmq_cluster" % prefix,
                    INFRA / "rabbitmq-cluster" / "docker-compose.yml",
                    [],
                )
            )
        else:
            result.append(
                Stack(
                    "%s_rabbitmq_single" % prefix,
                    INFRA / "docker-compose.yml",
                    ["rabbitmq"],
                )
            )
    elif DEMO_MODE == "kafka":
        if topology == "cluster":
            result.append(
                Stack(
                    "%s_kafka_cluster" % prefix,
                    INFRA / "kafka-cluster" / "docker-compose.yml",
                    [],
                )
            )
        else:
            result.append(
                Stack(
                    "%s_kafka_single" % prefix,
                    INFRA / "docker-compose.yml",
                    ["kafka"],
                )
            )
    return result


def compose_command(stack: Stack, arguments: List[str]) -> List[str]:
    command = [
        "docker",
        "compose",
        "--project-name",
        stack.name,
        "--file",
        str(stack.compose_file),
    ]
    env_file = INFRA / ".env"
    if stack.compose_file.parent == INFRA and env_file.exists():
        command.extend(["--env-file", str(env_file)])
    command.extend(arguments)
    return command


def run_command(command: List[str], check: bool = True) -> int:
    print("+ %s" % subprocess.list2cmdline(command), flush=True)
    return subprocess.run(command, cwd=str(ROOT), check=check).returncode


def capture_command(command: List[str]) -> subprocess.CompletedProcess:
    print("+ %s" % subprocess.list2cmdline(command), flush=True)
    return subprocess.run(
        command,
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        check=False,
    )


def ensure_env() -> None:
    target = INFRA / ".env"
    source = INFRA / ".env.example"
    if not target.exists() and source.exists():
        target.write_bytes(source.read_bytes())


def required_ports(topology: str) -> Dict[int, str]:
    """Return every fixed host port that the selected Compose stacks publish."""
    if DEMO_MODE == "memory":
        return {}

    if topology == "single":
        result = {6379: "Redis"}
    elif topology == "sentinel":
        result = {
            6379: "Redis Sentinel master",
            6380: "Redis Sentinel replica 1",
            6381: "Redis Sentinel replica 2",
            26379: "Redis Sentinel 1",
            26380: "Redis Sentinel 2",
            26381: "Redis Sentinel 3",
        }
    else:
        result = {
            port: "Redis Cluster node %s" % (index + 1)
            for index, port in enumerate(range(7000, 7006))
        }

    if DEMO_MODE == "rabbitmq":
        if topology == "cluster":
            for index, port in enumerate(range(5672, 5675), start=1):
                result[port] = "RabbitMQ node %s AMQP" % index
            for index, port in enumerate(range(15672, 15675), start=1):
                result[port] = "RabbitMQ node %s management" % index
            for index, port in enumerate(range(25672, 25675), start=1):
                result[port] = "RabbitMQ node %s distribution" % index
        else:
            result[5672] = "RabbitMQ AMQP"
            result[15672] = "RabbitMQ management"
    elif DEMO_MODE == "kafka":
        if topology == "cluster":
            for index, port in enumerate(range(9094, 9097), start=1):
                result[port] = "Kafka broker %s" % index
        else:
            result[9092] = "Kafka"
    return result


def docker_port_owners(port: int) -> List[str]:
    result = subprocess.run(
        [
            "docker",
            "ps",
            "--filter",
            "publish=%s" % port,
            "--format",
            "{{.Names}}",
        ],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode:
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def port_is_available(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as connection:
        try:
            connection.bind(("0.0.0.0", port))
        except OSError:
            return False
    return True


def preflight_ports(topology: str) -> None:
    """Fail before Compose starts anything when a required port is occupied."""
    conflicts = []
    own_prefix = project_prefix()
    for port, service in required_ports(topology).items():
        if port_is_available(port):
            continue
        owners = docker_port_owners(port)
        if owners and all(owner.startswith(own_prefix) for owner in owners):
            continue
        conflicts.append((port, service, owners))

    if not conflicts:
        return

    lines = [
        "Cannot start the %s Demo infrastructure because required ports "
        "are already in use:" % topology
    ]
    for port, service, owners in conflicts:
        owner_text = ", ".join(owners) if owners else "a local process"
        lines.append("  - %s (%s): %s" % (port, service, owner_text))
    lines.extend(
        [
            "",
            "Stop the conflicting service/container, then run this command again.",
            "Docker lookup: docker ps --filter publish=<PORT>",
        ]
    )
    if sys.platform == "win32":
        lines.append("Windows lookup: netstat -ano | findstr :<PORT>")
    else:
        lines.append("Process lookup: lsof -nP -iTCP:<PORT> -sTCP:LISTEN")
    raise RuntimeError("\n".join(lines))


def up(topology: str) -> None:
    ensure_env()
    selected = stacks(topology)
    if not selected:
        print("Memory Demo does not require Docker infrastructure.")
        return
    print(
        "Demo mode: %s; topology: %s. Only this mode's required services "
        "will be started." % (DEMO_MODE, topology),
        flush=True,
    )
    preflight_ports(topology)
    for stack in selected:
        arguments = ["up", "--detach", "--wait"]
        arguments.extend(stack.services)
        run_command(compose_command(stack, arguments))


def down(topology: str) -> None:
    for stack in reversed(stacks(topology)):
        run_command(
            compose_command(
                stack,
                ["down", "--volumes", "--remove-orphans"],
            ),
            check=False,
        )


def status(topology: str) -> None:
    selected = stacks(topology)
    if not selected:
        print("Memory Demo does not require Docker infrastructure.")
        return
    for stack in selected:
        run_command(compose_command(stack, ["ps"]), check=False)


def plan(topology: str) -> None:
    selected = stacks(topology)
    if not selected:
        print("memory: no Docker stack")
        return
    for stack in selected:
        services = ",".join(stack.services) if stack.services else "all"
        print("%s | %s | %s" % (stack.name, stack.compose_file, services))


def run_demo(topology: str) -> int:
    up(topology)
    log_dir = ROOT / "artifacts" / "demo-verification" / topology
    log_dir.mkdir(parents=True, exist_ok=True)
    environment = dict(os.environ)
    environment["SCRAPY_CFFI_DEMO_TOPOLOGY"] = topology
    environment["SCRAPY_CFFI_DEMO_LOG"] = str(log_dir / "demo.log")
    console_log = log_dir / "console.log"
    print("Crawler log: %s" % console_log)
    try:
        with console_log.open("w", encoding="utf-8") as output:
            return subprocess.run(
                [sys.executable, "-u", "runner.py"],
                cwd=str(ROOT),
                env=environment,
                stdout=output,
                stderr=subprocess.STDOUT,
                check=False,
            ).returncode
    finally:
        down(topology)


def wait_for_port(port: int, process: subprocess.Popen) -> None:
    deadline = time.monotonic() + 20
    while time.monotonic() < deadline:
        if process.poll() is not None:
            raise RuntimeError("Demo server exited before port %s was ready" % port)
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as connection:
            connection.settimeout(0.25)
            if connection.connect_ex(("127.0.0.1", port)) == 0:
                return
        time.sleep(0.2)
    raise TimeoutError("Timed out waiting for demo server port %s" % port)


def available_port(preferred: int) -> int:
    for port in range(preferred, preferred + 100):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as connection:
            try:
                connection.bind(("127.0.0.1", port))
            except OSError:
                continue
            return port
    raise RuntimeError("No free local port found from %s" % preferred)


def stop_process(process: subprocess.Popen) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=5)


def seed_request(
    environment: Dict[str, str],
    log_dir: Path,
    start_url: str,
) -> None:
    if DEMO_MODE == "memory":
        return
    if DEMO_MODE == "kafka":
        publisher_environment = dict(environment)
        publisher_environment["SCRAPY_CFFI_START_URL"] = start_url
        if environment.get("SCRAPY_CFFI_DEMO_TOPOLOGY") == "cluster":
            publisher_environment["SCRAPY_CFFI_KAFKA_BOOTSTRAP_SERVERS"] = (
                "127.0.0.1:9094,127.0.0.1:9095,127.0.0.1:9096"
            )
        with (log_dir / "enqueue.log").open("w", encoding="utf-8") as output:
            subprocess.run(
                [sys.executable, "scripts/push_kafka_demo.py"],
                cwd=str(ROOT),
                env=publisher_environment,
                stdout=output,
                stderr=subprocess.STDOUT,
                timeout=30,
                check=True,
            )
        return
    code = (
        "import asyncio\n"
        "from runner import DEFAULT_SPIDER\n"
        "from settings import create_settings\n"
        "from scrapy_cffi import build_resource_service\n"
        "async def main():\n"
        "    settings = create_settings(DEFAULT_SPIDER)\n"
        "    resources = build_resource_service(settings, asyncio.Event())\n"
        "    await resources.start()\n"
    )
    if DEMO_MODE == "redis":
        code += (
            "    await resources.redis.rpush("
            f"'customRedisSpider_test', {start_url!r})\n"
        )
    elif DEMO_MODE == "rabbitmq":
        code += (
            "    await resources.rabbitmq.push("
            f"'scrapy_cffi', {start_url.encode()!r})\n"
        )
    code += (
        "    await resources.close()\n"
        "asyncio.run(main())\n"
    )
    with (log_dir / "enqueue.log").open("w", encoding="utf-8") as output:
        subprocess.run(
            [sys.executable, "-c", code],
            cwd=str(ROOT),
            env=environment,
            stdout=output,
            stderr=subprocess.STDOUT,
            timeout=30,
            check=True,
        )


def assert_nonpersistent_cleanup(topology: str, log_dir: Path) -> None:
    if DEMO_MODE == "memory":
        return
    selected = stacks(topology)
    redis_stack = selected[0]
    checks = []
    if topology == "single":
        checks.append(
            (
                "redis",
                redis_stack,
                ["exec", "-T", "redis", "redis-cli", "--scan"],
                ("customRedisSpider", "dupefilter", "session"),
            )
        )
    elif topology == "sentinel":
        checks.append(
            (
                "redis",
                redis_stack,
                ["exec", "-T", "redis-master", "redis-cli", "--scan"],
                ("customRedisSpider", "dupefilter", "session"),
            )
        )
    else:
        for index, port in enumerate(range(7000, 7006), start=1):
            checks.append(
                (
                    "redis-node%s" % index,
                    redis_stack,
                    [
                        "exec",
                        "-T",
                        "redis-node%s" % index,
                        "redis-cli",
                        "-p",
                        str(port),
                        "--scan",
                    ],
                    ("customRedisSpider", "dupefilter", "session"),
                )
            )

    if DEMO_MODE == "rabbitmq":
        rabbit_stack = selected[-1]
        rabbit_service = "rabbit1" if topology == "cluster" else "rabbitmq"
        checks.append(
            (
                "rabbitmq",
                rabbit_stack,
                [
                    "exec",
                    "-T",
                    rabbit_service,
                    "rabbitmqctl",
                    "list_queues",
                    "-q",
                    "name",
                ],
                ("scrapy_cffi",),
            )
        )
    elif DEMO_MODE == "kafka":
        kafka_stack = selected[-1]
        kafka_service = "kafka1" if topology == "cluster" else "kafka"
        bootstrap = "127.0.0.1:19092" if topology == "cluster" else "127.0.0.1:9092"
        checks.append(
            (
                "kafka",
                kafka_stack,
                [
                    "exec",
                    "-T",
                    kafka_service,
                    "/opt/kafka/bin/kafka-topics.sh",
                    "--bootstrap-server",
                    bootstrap,
                    "--list",
                ],
                ("customRedisSpider_start", "customRedisSpider_requests"),
            )
        )

    evidence = []
    failures = []
    for label, stack, args, forbidden in checks:
        result = capture_command(compose_command(stack, args))
        output = "%s\n%s" % (result.stdout, result.stderr)
        evidence.append("[%s]\n%s" % (label, output.strip()))
        if result.returncode != 0:
            failures.append("%s inspection failed" % label)
            continue
        leaked = [value for value in forbidden if value in output]
        if leaked:
            failures.append("%s retained %s" % (label, ", ".join(leaked)))
    (log_dir / "cleanup.log").write_text(
        "\n\n".join(evidence) + "\n",
        encoding="utf-8",
    )
    if failures:
        raise RuntimeError("; ".join(failures))


def verify(topology: str, interrupt: bool = False) -> None:
    up(topology)
    log_dir = ROOT / "artifacts" / "demo-verification" / topology
    log_dir.mkdir(parents=True, exist_ok=True)
    environment = dict(os.environ)
    http_port = available_port(18002)
    websocket_port = available_port(18765)
    environment["SCRAPY_CFFI_DEMO_TOPOLOGY"] = topology
    environment["SCRAPY_CFFI_DEMO_LOG"] = str(log_dir / "demo.log")
    environment["SCRAPY_CFFI_DEMO_HTTP_PORT"] = str(http_port)
    environment["SCRAPY_CFFI_DEMO_WS_PORT"] = str(websocket_port)
    server_dir = ROOT / "demo_support" / "server"
    handles = [
        (log_dir / "http_server.log").open("w", encoding="utf-8"),
        (log_dir / "websocket_server.log").open("w", encoding="utf-8"),
    ]
    processes = []
    try:
        processes = [
            subprocess.Popen(
                [
                    sys.executable,
                    "-u",
                    "-m",
                    "uvicorn",
                    "fastApiServer:app",
                    "--host",
                    "127.0.0.1",
                    "--port",
                    str(http_port),
                ],
                cwd=str(server_dir),
                env=environment,
                stdout=handles[0],
                stderr=subprocess.STDOUT,
            ),
            subprocess.Popen(
                [sys.executable, "-u", "ws_server.py"],
                cwd=str(server_dir),
                env=environment,
                stdout=handles[1],
                stderr=subprocess.STDOUT,
            ),
        ]
        wait_for_port(http_port, processes[0])
        wait_for_port(websocket_port, processes[1])
        seed_request(
            environment,
            log_dir,
            "http://127.0.0.1:%s" % http_port,
        )
        console_path = log_dir / "console.log"
        with console_path.open("w", encoding="utf-8") as output:
            if interrupt:
                environment["SCRAPY_CFFI_VERIFY_HOLD_OPEN"] = "1"
                creationflags = (
                    subprocess.CREATE_NEW_PROCESS_GROUP
                    if sys.platform == "win32"
                    else 0
                )
                crawler_process = subprocess.Popen(
                    [sys.executable, "-u", "runner.py"],
                    cwd=str(ROOT),
                    env=environment,
                    stdout=output,
                    stderr=subprocess.STDOUT,
                    creationflags=creationflags,
                )
                try:
                    time.sleep(
                        10
                        if topology == "cluster" and DEMO_MODE == "kafka"
                        else 4
                    )
                    if crawler_process.poll() is not None:
                        raise RuntimeError(
                            "crawler exited before interrupt: %s"
                            % crawler_process.returncode
                        )
                    if sys.platform == "win32":
                        crawler_process.send_signal(signal.CTRL_BREAK_EVENT)
                    else:
                        crawler_process.send_signal(signal.SIGINT)
                    crawler_process.wait(timeout=30)
                    if crawler_process.returncode:
                        raise RuntimeError(
                            "interrupted crawler exited with code %s"
                            % crawler_process.returncode
                        )
                finally:
                    stop_process(crawler_process)
            else:
                crawler_code = (
                    "import asyncio\n"
                    "from runner import advance_main\n"
                    "async def verify():\n"
                    "    crawler, engine_task = await advance_main()\n"
                    "    try:\n"
                    "        await asyncio.sleep(%s)\n"
                    "    finally:\n"
                    "        await crawler.shutdown()\n"
                    "    await asyncio.wait_for(engine_task, timeout=15)\n"
                    "asyncio.run(verify())\n"
                ) % (15 if topology == "cluster" and DEMO_MODE == "kafka" else 6)
                subprocess.run(
                    [sys.executable, "-c", crawler_code],
                    cwd=str(ROOT),
                    env=environment,
                    stdout=output,
                    stderr=subprocess.STDOUT,
                    timeout=35,
                    check=True,
                )
        assert_nonpersistent_cleanup(topology, log_dir)
        for process in reversed(processes):
            stop_process(process)
        for handle in handles:
            handle.close()
        processes = []
        handles = []

        console = console_path.read_text(encoding="utf-8", errors="replace")
        websocket = (log_dir / "websocket_server.log").read_text(
            encoding="utf-8",
            errors="replace",
        )
        failures = []
        if not (log_dir / "demo.log").is_file():
            failures.append("demo.log is missing")
        if not interrupt and '"method":"GET"' not in console:
            failures.append("HTTP callback evidence is missing")
        if not interrupt and "received:" not in websocket:
            failures.append("WebSocket incremental request evidence is missing")
        if interrupt and ">>> [signal] Received stop signal" not in console:
            failures.append("Ctrl+C signal evidence is missing")
        if "Traceback (most recent call last)" in console:
            failures.append("crawler console contains a traceback")
        if failures:
            raise RuntimeError("; ".join(failures))
        (log_dir / "result.txt").write_text(
            (
                "status=PASS\nmode=%s\ntopology=%s\ninterrupt=%s\n"
                "http_port=%s\nwebsocket_port=%s\n"
            )
            % (DEMO_MODE, topology, interrupt, http_port, websocket_port),
            encoding="utf-8",
        )
        print("PASS: %s / %s; logs: %s" % (DEMO_MODE, topology, log_dir))
    except BaseException as exc:
        (log_dir / "result.txt").write_text(
            "status=FAIL\nmode=%s\ntopology=%s\nerror=%r\n"
            % (DEMO_MODE, topology, exc),
            encoding="utf-8",
        )
        raise
    finally:
        for process in reversed(processes):
            stop_process(process)
        for handle in handles:
            handle.close()
        down(topology)


def parse_args(arguments: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Manage and verify the Docker infrastructure for this generated Demo."
        )
    )
    parser.add_argument(
        "command",
        choices=(
            "plan",
            "up",
            "reset",
            "down",
            "status",
            "run",
            "verify",
            "verify-all",
            "verify-interrupt",
            "verify-interrupt-all",
        ),
    )
    parser.add_argument(
        "topology",
        nargs="?",
        default="single",
        choices=TOPOLOGIES,
    )
    return parser.parse_args(arguments)


def main() -> int:
    try:
        args = parse_args()
        if args.command == "plan":
            plan(args.topology)
        elif args.command == "up":
            up(args.topology)
        elif args.command == "down":
            down(args.topology)
        elif args.command == "reset":
            down(args.topology)
            up(args.topology)
        elif args.command == "status":
            status(args.topology)
        elif args.command == "verify":
            verify(args.topology)
        elif args.command == "verify-all":
            selected = ("single",) if DEMO_MODE == "memory" else TOPOLOGIES
            for topology in selected:
                verify(topology)
        elif args.command == "verify-interrupt":
            verify(args.topology, interrupt=True)
        elif args.command == "verify-interrupt-all":
            selected = ("single",) if DEMO_MODE == "memory" else TOPOLOGIES
            for topology in selected:
                verify(topology, interrupt=True)
        else:
            return run_demo(args.topology)
        return 0
    except (RuntimeError, subprocess.CalledProcessError) as exc:
        print("ERROR: %s" % exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
