# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x04\x64\x65mo\"8\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\"\xeb\x01\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12\x15\n\x08nickname\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06\x65mails\x18\x05 \x03(\t\x12\x30\n\nattributes\x18\x06 \x03(\x0b\x32\x1c.demo.Person.AttributesEntry\x12\x1e\n\x07\x61\x64\x64ress\x18\x07 \x01(\x0b\x32\r.demo.Address\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0b\n\t_nicknameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_PERSON_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_ADDRESS']._serialized_start=23
  _globals['_ADDRESS']._serialized_end=79
  _globals['_PERSON']._serialized_start=82
  _globals['_PERSON']._serialized_end=317
  _globals['_PERSON_ATTRIBUTESENTRY']._serialized_start=255
  _globals['_PERSON_ATTRIBUTESENTRY']._serialized_end=304
# @@protoc_insertion_point(module_scope)
