"""Project-local Docker manager generated by ``scrapy-cffi demo``."""

import argparse
import hashlib
import os
from pathlib import Path
import signal
import socket
import subprocess
import sys
import time
from typing import Dict, List, NamedTuple, Optional

from demo_topology import DEMO_MODE


ROOT = Path(__file__).resolve().parent
INFRA = ROOT / "infra"
TOPOLOGIES = ("single", "sentinel", "cluster")


class Stack(NamedTuple):
    name: str
    compose_file: Path
    services: List[str]


def project_prefix() -> str:
    digest = hashlib.sha1(str(ROOT).encode("utf-8")).hexdigest()[:8]
    return "scrapy_cffi_demo_%s" % digest


def stacks(topology: str) -> List[Stack]:
    prefix = project_prefix()
    if DEMO_MODE == "memory":
        return []

    result = []
    if topology == "single":
        services = ["redis"]
        if DEMO_MODE == "rabbitmq":
            services.append("rabbitmq")
        elif DEMO_MODE == "kafka":
            services.append("kafka")
        result.append(
            Stack(
                "%s_single" % prefix,
                INFRA / "docker-compose.yml",
                services,
            )
        )
        return result

    redis_name = "redis-sentinel" if topology == "sentinel" else "redis-cluster"
    result.append(
        Stack(
            "%s_%s" % (prefix, redis_name.replace("-", "_")),
            INFRA / redis_name / "docker-compose.yml",
            [],
        )
    )
    if DEMO_MODE == "rabbitmq":
        if topology == "cluster":
            result.append(
                Stack(
                    "%s_rabbitmq_cluster" % prefix,
                    INFRA / "rabbitmq-cluster" / "docker-compose.yml",
                    [],
                )
            )
        else:
            result.append(
                Stack(
                    "%s_rabbitmq_single" % prefix,
                    INFRA / "docker-compose.yml",
                    ["rabbitmq"],
                )
            )
    elif DEMO_MODE == "kafka":
        if topology == "cluster":
            result.append(
                Stack(
                    "%s_kafka_cluster" % prefix,
                    INFRA / "kafka-cluster" / "docker-compose.yml",
                    [],
                )
            )
        else:
            result.append(
                Stack(
                    "%s_kafka_single" % prefix,
                    INFRA / "docker-compose.yml",
                    ["kafka"],
                )
            )
    return result


def compose_command(stack: Stack, arguments: List[str]) -> List[str]:
    command = [
        "docker",
        "compose",
        "--project-name",
        stack.name,
        "--file",
        str(stack.compose_file),
    ]
    env_file = INFRA / ".env"
    if stack.compose_file.parent == INFRA and env_file.exists():
        command.extend(["--env-file", str(env_file)])
    command.extend(arguments)
    return command


def run_command(command: List[str], check: bool = True) -> int:
    print("+ %s" % subprocess.list2cmdline(command), flush=True)
    return subprocess.run(command, cwd=str(ROOT), check=check).returncode


def capture_command(command: List[str]) -> subprocess.CompletedProcess:
    print("+ %s" % subprocess.list2cmdline(command), flush=True)
    return subprocess.run(
        command,
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        check=False,
    )


def ensure_env() -> None:
    target = INFRA / ".env"
    source = INFRA / ".env.example"
    if not target.exists() and source.exists():
        target.write_bytes(source.read_bytes())


def up(topology: str) -> None:
    ensure_env()
    selected = stacks(topology)
    if not selected:
        print("Memory Demo does not require Docker infrastructure.")
        return
    for stack in selected:
        arguments = ["up", "--detach", "--wait"]
        arguments.extend(stack.services)
        run_command(compose_command(stack, arguments))


def down(topology: str) -> None:
    for stack in reversed(stacks(topology)):
        run_command(
            compose_command(
                stack,
                ["down", "--volumes", "--remove-orphans"],
            ),
            check=False,
        )


def status(topology: str) -> None:
    selected = stacks(topology)
    if not selected:
        print("Memory Demo does not require Docker infrastructure.")
        return
    for stack in selected:
        run_command(compose_command(stack, ["ps"]), check=False)


def plan(topology: str) -> None:
    selected = stacks(topology)
    if not selected:
        print("memory: no Docker stack")
        return
    for stack in selected:
        services = ",".join(stack.services) if stack.services else "all"
        print("%s | %s | %s" % (stack.name, stack.compose_file, services))


def run_demo(topology: str) -> int:
    up(topology)
    log_dir = ROOT / "artifacts" / "demo-verification" / topology
    log_dir.mkdir(parents=True, exist_ok=True)
    environment = dict(os.environ)
    environment["SCRAPY_CFFI_DEMO_TOPOLOGY"] = topology
    environment["SCRAPY_CFFI_DEMO_LOG"] = str(log_dir / "demo.log")
    console_log = log_dir / "console.log"
    print("Crawler log: %s" % console_log)
    try:
        with console_log.open("w", encoding="utf-8") as output:
            return subprocess.run(
                [sys.executable, "-u", "runner.py"],
                cwd=str(ROOT),
                env=environment,
                stdout=output,
                stderr=subprocess.STDOUT,
                check=False,
            ).returncode
    finally:
        down(topology)


def wait_for_port(port: int, process: subprocess.Popen) -> None:
    deadline = time.monotonic() + 20
    while time.monotonic() < deadline:
        if process.poll() is not None:
            raise RuntimeError("Demo server exited before port %s was ready" % port)
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as connection:
            connection.settimeout(0.25)
            if connection.connect_ex(("127.0.0.1", port)) == 0:
                return
        time.sleep(0.2)
    raise TimeoutError("Timed out waiting for demo server port %s" % port)


def available_port(preferred: int) -> int:
    for port in range(preferred, preferred + 100):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as connection:
            try:
                connection.bind(("127.0.0.1", port))
            except OSError:
                continue
            return port
    raise RuntimeError("No free local port found from %s" % preferred)


def stop_process(process: subprocess.Popen) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=5)


def seed_request(
    environment: Dict[str, str],
    log_dir: Path,
    start_url: str,
) -> None:
    if DEMO_MODE == "memory":
        return
    code = (
        "import asyncio\n"
        "from runner import DEFAULT_SPIDER\n"
        "from settings import create_settings\n"
        "async def main():\n"
        "    settings = create_settings(DEFAULT_SPIDER)\n"
    )
    if DEMO_MODE == "redis":
        code += (
            "    from scrapy_cffi.databases.redis import RedisManager\n"
            "    manager = RedisManager.from_redis_info("
            "asyncio.Event(), settings.REDIS_INFO)\n"
            "    await manager.rpush("
            f"'customRedisSpider_test', {start_url!r})\n"
        )
    elif DEMO_MODE == "rabbitmq":
        code += (
            "    from scrapy_cffi.mq.rabbitmq import RabbitMQManager\n"
            "    manager = RabbitMQManager.from_rabbitmq_info("
            "asyncio.Event(), settings.RABBITMQ_INFO, persist=False)\n"
            "    await manager.rpush("
            f"'scrapy_cffi', {start_url.encode()!r})\n"
        )
    else:
        code += (
            "    from scrapy_cffi.mq.kafka import KafkaManager\n"
            "    manager = KafkaManager.from_kafka_info("
            "asyncio.Event(), settings.KAFKA_INFO)\n"
            "    await manager.produce("
            f"'customRedisSpider_start', {start_url.encode()!r})\n"
        )
    code += (
        "    await manager.close()\n"
        "asyncio.run(main())\n"
    )
    with (log_dir / "enqueue.log").open("w", encoding="utf-8") as output:
        subprocess.run(
            [sys.executable, "-c", code],
            cwd=str(ROOT),
            env=environment,
            stdout=output,
            stderr=subprocess.STDOUT,
            timeout=30,
            check=True,
        )


def assert_nonpersistent_cleanup(topology: str, log_dir: Path) -> None:
    if DEMO_MODE == "memory":
        return
    selected = stacks(topology)
    redis_stack = selected[0]
    checks = []
    if topology == "single":
        checks.append(
            (
                "redis",
                redis_stack,
                ["exec", "-T", "redis", "redis-cli", "--scan"],
                ("customRedisSpider", "dupefilter", "session"),
            )
        )
    elif topology == "sentinel":
        checks.append(
            (
                "redis",
                redis_stack,
                ["exec", "-T", "redis-master", "redis-cli", "--scan"],
                ("customRedisSpider", "dupefilter", "session"),
            )
        )
    else:
        for index, port in enumerate(range(7000, 7006), start=1):
            checks.append(
                (
                    "redis-node%s" % index,
                    redis_stack,
                    [
                        "exec",
                        "-T",
                        "redis-node%s" % index,
                        "redis-cli",
                        "-p",
                        str(port),
                        "--scan",
                    ],
                    ("customRedisSpider", "dupefilter", "session"),
                )
            )

    if DEMO_MODE == "rabbitmq":
        rabbit_stack = selected[-1]
        rabbit_service = "rabbit1" if topology == "cluster" else "rabbitmq"
        checks.append(
            (
                "rabbitmq",
                rabbit_stack,
                [
                    "exec",
                    "-T",
                    rabbit_service,
                    "rabbitmqctl",
                    "list_queues",
                    "-q",
                    "name",
                ],
                ("scrapy_cffi",),
            )
        )
    elif DEMO_MODE == "kafka":
        kafka_stack = selected[-1]
        kafka_service = "kafka1" if topology == "cluster" else "kafka"
        bootstrap = "127.0.0.1:19092" if topology == "cluster" else "127.0.0.1:9092"
        checks.append(
            (
                "kafka",
                kafka_stack,
                [
                    "exec",
                    "-T",
                    kafka_service,
                    "/opt/kafka/bin/kafka-topics.sh",
                    "--bootstrap-server",
                    bootstrap,
                    "--list",
                ],
                ("customRedisSpider_start", "customRedisSpider_requests"),
            )
        )

    evidence = []
    failures = []
    for label, stack, args, forbidden in checks:
        result = capture_command(compose_command(stack, args))
        output = "%s\n%s" % (result.stdout, result.stderr)
        evidence.append("[%s]\n%s" % (label, output.strip()))
        if result.returncode != 0:
            failures.append("%s inspection failed" % label)
            continue
        leaked = [value for value in forbidden if value in output]
        if leaked:
            failures.append("%s retained %s" % (label, ", ".join(leaked)))
    (log_dir / "cleanup.log").write_text(
        "\n\n".join(evidence) + "\n",
        encoding="utf-8",
    )
    if failures:
        raise RuntimeError("; ".join(failures))


def verify(topology: str, interrupt: bool = False) -> None:
    up(topology)
    log_dir = ROOT / "artifacts" / "demo-verification" / topology
    log_dir.mkdir(parents=True, exist_ok=True)
    environment = dict(os.environ)
    http_port = available_port(18002)
    websocket_port = available_port(18765)
    environment["SCRAPY_CFFI_DEMO_TOPOLOGY"] = topology
    environment["SCRAPY_CFFI_DEMO_LOG"] = str(log_dir / "demo.log")
    environment["SCRAPY_CFFI_DEMO_HTTP_PORT"] = str(http_port)
    environment["SCRAPY_CFFI_DEMO_WS_PORT"] = str(websocket_port)
    server_dir = ROOT / "demo_server"
    handles = [
        (log_dir / "http_server.log").open("w", encoding="utf-8"),
        (log_dir / "websocket_server.log").open("w", encoding="utf-8"),
    ]
    processes = []
    try:
        processes = [
            subprocess.Popen(
                [
                    sys.executable,
                    "-u",
                    "-m",
                    "uvicorn",
                    "fastApiServer:app",
                    "--host",
                    "127.0.0.1",
                    "--port",
                    str(http_port),
                ],
                cwd=str(server_dir),
                env=environment,
                stdout=handles[0],
                stderr=subprocess.STDOUT,
            ),
            subprocess.Popen(
                [sys.executable, "-u", "ws_server.py"],
                cwd=str(server_dir),
                env=environment,
                stdout=handles[1],
                stderr=subprocess.STDOUT,
            ),
        ]
        wait_for_port(http_port, processes[0])
        wait_for_port(websocket_port, processes[1])
        seed_request(
            environment,
            log_dir,
            "http://127.0.0.1:%s" % http_port,
        )
        console_path = log_dir / "console.log"
        with console_path.open("w", encoding="utf-8") as output:
            if interrupt:
                creationflags = (
                    subprocess.CREATE_NEW_PROCESS_GROUP
                    if sys.platform == "win32"
                    else 0
                )
                crawler_process = subprocess.Popen(
                    [sys.executable, "-u", "runner.py"],
                    cwd=str(ROOT),
                    env=environment,
                    stdout=output,
                    stderr=subprocess.STDOUT,
                    creationflags=creationflags,
                )
                try:
                    time.sleep(
                        10
                        if topology == "cluster" and DEMO_MODE == "kafka"
                        else 4
                    )
                    if crawler_process.poll() is not None:
                        raise RuntimeError(
                            "crawler exited before interrupt: %s"
                            % crawler_process.returncode
                        )
                    if sys.platform == "win32":
                        crawler_process.send_signal(signal.CTRL_BREAK_EVENT)
                    else:
                        crawler_process.send_signal(signal.SIGINT)
                    crawler_process.wait(timeout=30)
                    if crawler_process.returncode:
                        raise RuntimeError(
                            "interrupted crawler exited with code %s"
                            % crawler_process.returncode
                        )
                finally:
                    stop_process(crawler_process)
            else:
                crawler_code = (
                    "import asyncio\n"
                    "from runner import advance_main\n"
                    "async def verify():\n"
                    "    crawler, engine_task = await advance_main()\n"
                    "    try:\n"
                    "        await asyncio.sleep(%s)\n"
                    "    finally:\n"
                    "        await crawler.shutdown()\n"
                    "    await asyncio.wait_for(engine_task, timeout=15)\n"
                    "asyncio.run(verify())\n"
                ) % (15 if topology == "cluster" and DEMO_MODE == "kafka" else 6)
                subprocess.run(
                    [sys.executable, "-c", crawler_code],
                    cwd=str(ROOT),
                    env=environment,
                    stdout=output,
                    stderr=subprocess.STDOUT,
                    timeout=35,
                    check=True,
                )
        assert_nonpersistent_cleanup(topology, log_dir)
        for process in reversed(processes):
            stop_process(process)
        for handle in handles:
            handle.close()
        processes = []
        handles = []

        console = console_path.read_text(encoding="utf-8", errors="replace")
        websocket = (log_dir / "websocket_server.log").read_text(
            encoding="utf-8",
            errors="replace",
        )
        failures = []
        if not (log_dir / "demo.log").is_file():
            failures.append("demo.log is missing")
        if not interrupt and '"method":"GET"' not in console:
            failures.append("HTTP callback evidence is missing")
        if not interrupt and "received:" not in websocket:
            failures.append("WebSocket incremental request evidence is missing")
        if interrupt and ">>> [signal] Received stop signal" not in console:
            failures.append("Ctrl+C signal evidence is missing")
        if "Traceback (most recent call last)" in console:
            failures.append("crawler console contains a traceback")
        if failures:
            raise RuntimeError("; ".join(failures))
        (log_dir / "result.txt").write_text(
            (
                "status=PASS\nmode=%s\ntopology=%s\ninterrupt=%s\n"
                "http_port=%s\nwebsocket_port=%s\n"
            )
            % (DEMO_MODE, topology, interrupt, http_port, websocket_port),
            encoding="utf-8",
        )
        print("PASS: %s / %s; logs: %s" % (DEMO_MODE, topology, log_dir))
    except BaseException as exc:
        (log_dir / "result.txt").write_text(
            "status=FAIL\nmode=%s\ntopology=%s\nerror=%r\n"
            % (DEMO_MODE, topology, exc),
            encoding="utf-8",
        )
        raise
    finally:
        for process in reversed(processes):
            stop_process(process)
        for handle in handles:
            handle.close()
        down(topology)


def parse_args(arguments: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Manage and verify the Docker infrastructure for this generated Demo."
        )
    )
    parser.add_argument(
        "command",
        choices=(
            "plan",
            "up",
            "reset",
            "down",
            "status",
            "run",
            "verify",
            "verify-all",
            "verify-interrupt",
            "verify-interrupt-all",
        ),
    )
    parser.add_argument(
        "topology",
        nargs="?",
        default="single",
        choices=TOPOLOGIES,
    )
    return parser.parse_args(arguments)


def main() -> int:
    args = parse_args()
    if args.command == "plan":
        plan(args.topology)
    elif args.command == "up":
        up(args.topology)
    elif args.command == "down":
        down(args.topology)
    elif args.command == "reset":
        down(args.topology)
        up(args.topology)
    elif args.command == "status":
        status(args.topology)
    elif args.command == "verify":
        verify(args.topology)
    elif args.command == "verify-all":
        selected = ("single",) if DEMO_MODE == "memory" else TOPOLOGIES
        for topology in selected:
            verify(topology)
    elif args.command == "verify-interrupt":
        verify(args.topology, interrupt=True)
    elif args.command == "verify-interrupt-all":
        selected = ("single",) if DEMO_MODE == "memory" else TOPOLOGIES
        for topology in selected:
            verify(topology, interrupt=True)
    else:
        return run_demo(args.topology)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
