from pathlib import Path
import shutil

from ._template_build import copytree_merge_text_safe, read_text_template, write_utf8_file


GENERATED_DIRS = {
    "redis-sentinel",
    "redis-cluster",
    "rabbitmq-cluster",
    "kafka-cluster",
}
GENERATED_FILES = {
    # Legacy geninfra versions copied these application-image files.
    ".dockerignore",
    "Dockerfile",
    ".env.example",
    ".gitignore",
    "docker-compose.yml",
    "destroy.ps1",
    "destroy.sh",
    "init.ps1",
    "init.sh",
    "reset.ps1",
    "reset.sh",
    "production-endpoints.example.toml",
    "topology.example.toml",
    "README.md",
}


def _clean_generated(target: Path) -> None:
    if not target.exists():
        print(f"Infrastructure directory does not exist: {target}")
        return

    removed = []
    for name in GENERATED_DIRS:
        path = target / name
        if path.exists():
            shutil.rmtree(path)
            removed.append(str(path.name))

    for name in GENERATED_FILES:
        path = target / name
        if path.exists():
            path.unlink()
            removed.append(str(path.name))

    # Preserve .env because it may contain developer-owned credentials/ports.
    try:
        if target.is_dir() and not any(target.iterdir()):
            target.rmdir()
            removed.append("<output-dir>")
    except OSError:
        pass

    if removed:
        print(f"Cleaned generated infra artifacts from: {target}")
    else:
        print(f"No generated infra artifacts found in: {target}")


def run(
    output_dir: str = "infra",
    redis_topology: str = "single",
    rabbitmq_topology: str = "single",
    kafka_topology: str = "single",
    generate_all: bool = False,
    clean: bool = False,
    overwrite: bool = True,
):
    base = Path(__file__).parent.parent
    template_dir = base / "templates"
    target = Path.cwd() / output_dir
    if clean:
        _clean_generated(target)
        return

    target.mkdir(parents=True, exist_ok=True)

    infra_files = (
        ".env.example",
        ".gitignore",
        "docker-compose.yml",
        "destroy.ps1",
        "destroy.sh",
        "init.ps1",
        "init.sh",
        "reset.ps1",
        "reset.sh",
    )
    for infra_file in infra_files:
        source = template_dir / "infra" / infra_file
        destination = target / infra_file
        if overwrite or not destination.exists():
            write_utf8_file(destination, read_text_template(source))
        if destination.suffix == ".sh":
            destination.chmod(0o755)

    if generate_all:
        redis_modes = ("sentinel", "cluster")
        rabbit_modes = ("cluster",)
        kafka_modes = ("cluster",)
    else:
        redis_modes = tuple(mode for mode in (redis_topology,) if mode != "single")
        rabbit_modes = tuple(mode for mode in (rabbitmq_topology,) if mode != "single")
        kafka_modes = tuple(mode for mode in (kafka_topology,) if mode != "single")

    summary_lines = [
        "- Single-node dev services: Redis, MySQL, PostgreSQL, MongoDB, RabbitMQ, Kafka",
        "- Initialize: `./init.sh` or `./init.ps1`",
        "- Reset all generated-stack data: `./reset.sh` or `./reset.ps1`",
        "- Destroy the selected project-local stack: `./destroy.sh` or `./destroy.ps1`",
        "- Docker topologies are local simulations only; production uses real infrastructure addresses",
    ]
    for mode in redis_modes:
        source = template_dir / "topologies" / f"redis-{mode}"
        destination = target / f"redis-{mode}"
        copytree_merge_text_safe(source, destination, overwrite=overwrite)
        summary_lines.append(f"- Redis override template: `{destination.name}`")

    for mode in rabbit_modes:
        source = template_dir / "topologies" / f"rabbitmq-{mode}"
        destination = target / f"rabbitmq-{mode}"
        copytree_merge_text_safe(source, destination, overwrite=overwrite)
        summary_lines.append(f"- RabbitMQ override template: `{destination.name}`")

    for mode in kafka_modes:
        source = template_dir / "topologies" / f"kafka-{mode}"
        destination = target / f"kafka-{mode}"
        copytree_merge_text_safe(source, destination, overwrite=overwrite)
        summary_lines.append(f"- Kafka override template: `{destination.name}`")

    profile_toml = template_dir / "topologies" / "production-endpoints.example.toml"
    profile_target = target / "production-endpoints.example.toml"
    if overwrite or not profile_target.exists():
        write_utf8_file(profile_target, read_text_template(profile_toml))

    readme = (
        "# Infra templates\n\n"
        "Generated by `scrapy-cffi infra generate`.\n\n"
        "## Development credentials\n\n"
        "| Service | Username | Password | Database / notes |\n"
        "| --- | --- | --- | --- |\n"
        "| Redis | - | - | No authentication |\n"
        "| MySQL | `root` | `123456` | `app_db`; host access enabled for local development |\n"
        "| PostgreSQL | `postgres` | `123456` | `app_db` |\n"
        "| MongoDB | - | - | Authentication disabled; initial DB `app_db` |\n"
        "| RabbitMQ | `guest` | `guest` | Management UI on port 15672 |\n"
        "| Kafka | - | - | PLAINTEXT development listener |\n\n"
        "Override these values in `.env`. Database initialization variables only "
        "apply when a data volume is first created; use `scrapy-cffi infra reset` "
        "to recreate disposable development data after changing credentials.\n\n"
        "This directory is an independent local-development stack; it is not part of the crawler image.\n"
        "The default `docker-compose.yml` provides Redis, MySQL, PostgreSQL, MongoDB, RabbitMQ, and Kafka.\n"
        "Run `./init.sh` (Linux/macOS) or `./init.ps1` (PowerShell) to initialize it.\n"
        "Reset deletes only volumes owned by the current crawler project and selected topology, then recreates it.\n"
        "Choose a local topology with `--topology`; reset recreates it, while destroy removes it without restart.\n"
        "The Compose project-name prefix comes from `default.infra_project_name` in the project-root `scrapy_cffi.toml`.\n"
        "New projects default it to `scrapy_cffi`; change it during development and keep it unique across concurrently running projects.\n"
        "This field is Docker tooling metadata only; crawler runtime settings and database/MQ clients do not read it.\n"
        "Services expose their normal host ports, and crawler code connects through the regular `*_INFO` addresses.\n"
        "Docker derives isolated container, network, and volume names from that prefix; do not add fixed `container_name` values.\n"
        "Edit `image:` entries in `docker-compose.yml` to pin or replace local-development images.\n"
        "When `--services` is omitted for `single`, Compose starts every service still defined in that file, so unwanted service blocks may be commented out.\n"
        "`infra up` fills missing templates without overwriting these edits; an explicit `infra generate` refreshes generated files.\n"
        "For non-single topologies, optional per-service templates are generated in subdirectories.\n"
        "`production-endpoints.example.toml` is a settings reference for real machine endpoints, not a Docker deployment file.\n\n"
        "Docs: [docs/usage/11-mq.md](https://github.com/aFunnyStrange/scrapy_cffi/blob/main/docs/usage/11-mq.md) · "
        "Broker tests: [tests/test_broker/README.md](https://github.com/aFunnyStrange/scrapy_cffi/blob/main/tests/test_broker/README.md)\n\n"
        "**Production boundary:** never deploy these data services with the crawler. "
        "Containerize only the crawler and configure real database/MQ machine addresses in settings.\n\n"
        + "\n".join(summary_lines)
        + "\n"
    )
    readme_target = target / "README.md"
    if overwrite or not readme_target.exists():
        write_utf8_file(readme_target, readme)
    print(f"Infrastructure templates generated at: {target}")
