from pathlib import Path
import shutil

from ._template_build import copytree_merge_text_safe, read_text_template, write_utf8_file


GENERATED_DIRS = {
    "redis-sentinel",
    "redis-cluster",
    "rabbitmq-cluster",
    "kafka-cluster",
}
GENERATED_FILES = {
    "topology.example.toml",
    "README.md",
}


def _clean_generated(target: Path) -> None:
    if not target.exists():
        print(f"Infrastructure directory does not exist: {target}")
        return

    removed = []
    for name in GENERATED_DIRS:
        p = target / name
        if p.exists():
            shutil.rmtree(p)
            removed.append(str(p.name))

    for name in GENERATED_FILES:
        p = target / name
        if p.exists():
            p.unlink()
            removed.append(str(p.name))

    # Remove empty root dir if it was created only for infra templates
    try:
        if target.is_dir() and (not any(target.iterdir())):
            target.rmdir()
            removed.append("<output-dir>")
    except OSError:
        pass

    if removed:
        print(f"Cleaned generated infra artifacts from: {target}")
    else:
        print(f"No generated infra artifacts found in: {target}")


def run(
    output_dir: str = "infra",
    redis_topology: str = "single",
    rabbitmq_topology: str = "single",
    kafka_topology: str = "single",
    generate_all: bool = False,
    clean: bool = False,
):
    base = Path(__file__).parent.parent
    template_dir = base / "templates"
    target = Path.cwd() / output_dir
    if clean:
        _clean_generated(target)
        return

    target.mkdir(parents=True, exist_ok=True)

    # Always generate a complete single-node baseline stack first.
    for docker_file in ["Dockerfile", "docker-compose.yml", ".gitignore", ".dockerignore"]:
        src = template_dir / "config" / docker_file
        dst = target / docker_file
        write_utf8_file(dst, read_text_template(src))

    if generate_all:
        # --all means: generate all core infra in single-node baseline mode.
        redis_modes = ()
        rabbit_modes = ()
        kafka_modes = ()
        redis_topology = "single"
        rabbitmq_topology = "single"
        kafka_topology = "single"
    else:
        redis_modes = tuple(m for m in (redis_topology,) if m != "single")
        rabbit_modes = tuple(m for m in (rabbitmq_topology,) if m != "single")
        kafka_modes = tuple(m for m in (kafka_topology,) if m != "single")

    summary_lines = ["- Base single-node stack generated: `docker-compose.yml` + `Dockerfile`"]
    for mode in redis_modes:
        src = template_dir / "topologies" / f"redis-{mode}"
        dst = target / f"redis-{mode}"
        copytree_merge_text_safe(src, dst)
        summary_lines.append(f"- Redis override template: `{dst.name}`")

    for mode in rabbit_modes:
        src = template_dir / "topologies" / f"rabbitmq-{mode}"
        dst = target / f"rabbitmq-{mode}"
        copytree_merge_text_safe(src, dst)
        summary_lines.append(f"- RabbitMQ override template: `{dst.name}`")

    for mode in kafka_modes:
        src = template_dir / "topologies" / f"kafka-{mode}"
        dst = target / f"kafka-{mode}"
        copytree_merge_text_safe(src, dst)
        summary_lines.append(f"- Kafka override template: `{dst.name}`")

    profile_toml = template_dir / "topologies" / "topology.example.toml"
    write_utf8_file(target / "topology.example.toml", read_text_template(profile_toml))

    readme = (
        "# Infra templates\n\n"
        "Generated by `scrapy-cffi geninfra`.\n"
        "Default output is a complete single-node stack in `docker-compose.yml`.\n"
        "For non-single topologies, optional per-service templates are generated in subdirectories.\n"
        "Fill `topology.example.toml` and adjust compose files for your environment.\n\n"
        + "\n".join(summary_lines)
        + "\n"
    )
    write_utf8_file(target / "README.md", readme)
    print(f"Infrastructure templates generated at: {target}")
